In [1]:
x= [1,2,3,4]

In [2]:
z = x

In [3]:
z

[1, 2, 3, 4]

In [4]:
x[0] = 4
x

[4, 2, 3, 4]

In [5]:
z

[4, 2, 3, 4]

In [ ]:
c = z.copy()

In [1]:
import pandas as pd
import numpy as np


df = pd.DataFrame(columns=["name", "age", "isCool", "score"], data=[["dan", 100, True, 20.2]])

In [12]:
df

  name  age  isCool  score
0  dan  100    True   20.2

In [2]:
new_data = pd.DataFrame([
    ["bob", 30, True, 85],
    ["lucas", 27, False, 60]
], columns=["name", "age", "isCool", "score"])

# Concatenating
df = pd.concat([df, new_data], ignore_index=True)
df

    name  age  isCool  score
0    dan  100    True   20.2
1    bob   30    True   85.0
2  lucas   27   False   60.0

In [3]:
df = df.drop(index=1)  # removes row with index 2
df

    name  age  isCool  score
0    dan  100    True   20.2
2  lucas   27   False   60.0

In [ ]:
import math

x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

n = len(x)

mean_x = sum(x) / n
mean_y = sum(y) / n

num = 0
denom_x = 0
denom_y = 0

for i in range(n):
    dx = x[i] - mean_x
    dy = y[i] - mean_y
    
    num += dx * dy
    denom_x += dx * dx
    denom_y += dy * dy

val = denom_x * denom_y

corr = num / math.sqrt(denom_x * denom_y)

print(corr)
print(val)

1.0
100.0

In [ ]:
import math

x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

n = len(x)

mean_x = sum(x) / n
mean_y = sum(y) / n

num = 0
denom_x = 0
denom_y = 0

for i in range(n):
    dx = x[i] - mean_x
    dy = y[i] - mean_y
    
    num += dx * dy
    denom_x += dx * dx
    denom_y += dy * dy

val = denom_x * denom_y

print(val)

100.0

In [5]:
math.sqrt(0)

0.0

In [16]:
df.to_csv("test.csv")

In [ ]:
# ,name,age,isCool,score
# 0,dan,100,True,20.2
# 1,bob,30,True,85.0
# 2,lucas,27,False,60.0
# 3,bob,30,True,85.0
# 4,lucas,27,False,60.0